config/routes.rb
Rails.application.routes.draw do
  root to: "chatrooms#index"
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :private_chatrooms

  devise_for :users, :controllers => { :registrations => 'users/registrations' }
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy
  belongs_to :owner, class_name: "User", foreign_key: "user_id"

  validates :owner, presence: true
  validates :name, presence: { message: "can't be blank" }, length: { in: 4..64, message: "must be between 4 and 64 characters" }, uniqueness: { message: "already exists" }

  scope :public_chatrooms, -> { where(private_chatroom: false) }
  scope :private_chatrooms, -> { where(private_chatroom: true) }

  def self.private_chatroom_for_users(users)
    user_ids = users.map(&:id).sort
    name = 'private_chatroom_' + user_ids.join("_")

    if chatroom = private_chatrooms.where(name: name).first
      chatroom
    else
      chatroom = new(name: name, private_chatroom: true)
      chatroom.user_id = users[0].id
      chatroom.users << users
      chatroom.save
      chatroom
    end
  end

  def owner_name
    owner.username
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  def index
    @chatrooms = Chatroom.public_chatrooms
  end

  def show
    authorize @chatroom
    @messages = @chatroom.messages.latest
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id)
  end

  def new
    @chatroom = Chatroom.new
  end

  def edit
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.owner = current_user

    respond_to do |format|
      if @chatroom.save
        @chatroom.users << current_user
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_form.html.erb
<%= form_for(chatroom) do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<div class="container-fluid">
  <div class="row" style="padding-bottom:20px;">
    <div class="col-xs-12">
      <h1 style="display:inline">Chatrooms</h1><span style="float:right"><%= link_to 'New Chatroom', new_chatroom_path, class: "btn btn-primary" %></span>
    </div>
  </div>
  <% @chatrooms.each do |chatroom| %>
    <div class="row" style="padding-top:15px;">
      <div class="col-xs-3">
        <%= link_to chatroom do %>
          <%= chatroom.name %> (<%= chatroom.owner_name %>)
        <% end %>
      </div>
      <div class="col-xs-9">
        <% if current_user && chatroom.users.map(&:id).include?(current_user.id) %>
          <%= link_to 'Leave chatroom', chatroom_chatroom_users_path(chatroom), method: :delete, class: "btn btn-sm btn-default" %>
        <% else %>
          <%= link_to 'Join chatroom', chatroom_chatroom_users_path(chatroom), method: :post, class: "btn btn-sm btn-success" %>
        <% end %>
        <% if policy(chatroom).update? %>
          <%= link_to 'Edit', edit_chatroom_path(chatroom), class: "btn btn-sm btn-warning" %>
          <%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<div style="padding-bottom:15px;">
  <h4 style="display:inline">
    <strong><u><%= @chatroom.name %> chatroom</u></strong>
  </h4>
  <span style="float:right">
    <%= link_to "Back to chatrooms", chatrooms_path %>
  </span>
</div>

<% unread_messages = false %>
<div data-behavior="messages" data-chatroom-id="<%= @chatroom.id %>">
  <% @messages.each do |message| %>
    <% if !unread_messages && @chatroom_user.checked_at < message.created_at %>
      <% unread_messages = true %>
      <div class="strike"><span>Unread messages</span></div>
    <% end %>

    <%= render message %>
  <% end %>
</div>

<%= form_for [@chatroom, Message.new] do |f| %>
  <%= f.text_area :body, rows: 1, autofocus: true, class: "form-control" %>
<% end %>