config/routes.rb
Rails.application.routes.draw do
  root to: "chatrooms#index"
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :private_chatrooms

  devise_for :users, :controllers => { :registrations => 'users/registrations' }
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="container-fluid flash-container">
  <% flash.each do |type, message| %>
    <div class= "alert flash-alert <%= bootstrap_alert_class_for(type) %>">
      <button type="button" class="close" data-dismiss="alert">&times;</button> 
      <%= message %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if user_signed_in? %>
      <%= tag :meta, name: "current-user", data: { id: current_user.id } %>
    <% end %>

    <link href='//fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div class="header">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <div class="navbar-brand"><%= link_to "ChatApp", root_path %></div>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="http://edgeguides.rubyonrails.org/action_cable_overview.html" target="_blank">THIS APP IS MADE WITH ACTION CABLE</a>
            </li>
            <% if user_signed_in? %>
              <%= yield :right_nav %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "SIGN UP", new_user_registration_path %></li>
              <li><%= link_to "LOGIN", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container-fluid" style="margin-top:70px;">
      <div class="row">
        <div class="col-sm-2" style="position:fixed; top:70px; left:0px;">
          <% if user_signed_in? %>
            <h5>My Chatrooms</h5>
            <ul>
              <% current_user.chatrooms.public_chatrooms.each do |chatroom| %>
                <li><%= link_to chatroom.name, chatroom, data: { behavior: "chatroom-link", chatroom_id: chatroom.id } %></li>
              <% end %>
            </ul>

            <h5>Users</h5>
            <ul>
              <% (User.all - [current_user]).each do |user| %>
                <li><%= link_to user.username, private_chatroom_path(user.id), data: { behavior: "chatroom-link", chatroom_id: Chatroom.private_chatroom_for_users([current_user, user]).id } %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <div class="col-sm-8 col-sm-offset-2">
          <%= render 'layouts/flash_messages' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>